<?php
// $Id$
/**
 * @author Bruno Massa
 * @file addresses.module
 * You can associate a geographic address with content and users.
 */

/**
 * Each address field can be: displayed, required, hidden or not
 * used at all
 */
define('ADDRESSES_FIELD_NONE',      0);
define('ADDRESSES_FIELD_SHOW',      1);
define('ADDRESSES_FIELD_REQUIRED',  2);
define('ADDRESSES_FIELD_HIDDEN',    3);

/**
 * Implementation of hook_addressfieldapi().
 *
 * Its a specific Addresses module hook function, to
 * allow other modules to add more fields to the addresses
 */
function addresses_addressesfieldapi($op, $fields = array(), $values = array()) {
  if ($op == 'fields') {
    return array(
      'aname' => array(
        'type'        => 'varchar',
        'length'      => 75,
        'description' => t('The nickname of this address, like "Home", "Office", "Anna\'s appartment"'),
        'display'     => ADDRESSES_FIELD_NONE,
        'title'       => t('Address Name'),
      ),
      'street' => array(
        'type'        => 'varchar',
        'length'      => 255,
        'description' => t('Street, number...'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Street'),
      ),
      'additional' => array(
        'type'        => 'varchar',
        'length'      => 255,
        'description' => t('More info like appartment block, number or address reference'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Additional'),
      ),
      'city' => array(
        'type'        => 'varchar',
        'length'      => 255,
        'description' => t('Name of the city'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('City'),
      ),
      'province' => array(
        'type'        => 'varchar',
        'length'      => 16,
        'description' => t('Name of the state/province/county/territory'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Province'),
      ),
      'country' => array(
        'type'        => 'varchar',
        'length'      => 2,
        'description' => t('The ISO alpha 3 code of each country (its a 2-digit code)'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Country'),
      ),
      'postal_code' => array(
        'type'        => 'varchar',
        'length'      => 16,
        'description' => t('The address postal code (ZIP code for US people)'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Postal code'),
      ),
      'is_primary' => array(
        'type'        => 'int',
        'size'        => 'tiny',
        'default'     => 0,
        'description' => t('Mark it as the primary address or not (default is not)'),
        'display'     => ADDRESSES_FIELD_NONE,
        'title'       => t('Primary Address Checkbox'),
      )
    );
  }
  elseif ($op == 'form') {
    module_load_include('settings.inc', 'addresses');
    return _addresses_addressesfieldapi_form($fields, $values);
  }
}

/**
 * Implementation of FAPI hook_elements().
 *
 * Any FAPI callbacks needed for individual widgets can be declared here,
 * and the element will be passed to those callbacks for processing.
 *
 * Drupal will automatically theme the element using a theme with
 * the same name as the hook_elements key.
 *
 * Autocomplete_path is not used by text_widget but other widgets can use it
 * (see nodereference and userreference).
 */
function addresses_elements() {
  // Get a list of all address-related fields
  $ftypes = module_invoke_all('addressesfieldapi', 'fields');
  foreach (array_keys($ftypes) as $ftype) {
    $fields[] = $ftype;
  }

  return array(
    'addresses_elements' => array(
      '#columns'  => $fields,
      '#delta'    => 0,
      '#input'    => TRUE,
      '#process'  => array('addresses_elements_process'),
    )
  );
}

/**
 * Generate the address "field", creating all form fields
 *
 * @return
 *   Array. Form fields
 */
function addresses_elements_process($element, $edit, $form_state, $form) {
  $fields = $element['#fields'];
  $values = $element['#default_value'];

  // Reset the required fields based on the general required value
  if (empty($element['#required'])) {
    foreach ($fields as $field => $required) {
      if ($required == ADDRESSES_FIELD_REQUIRED) {
        $fields[$field] = ADDRESSES_FIELD_SHOW;
      }
    }
  }

  // Reset unwanted attributes
  $element['#title'] = '';
  $element['#description'] = '';

  // If its a existing address, save the Address ID
  // for further processing
  if (!empty($values['aid'])) {
    $element['aid'] = array(
      '#type'   => 'hidden',
      '#value'  => $values['aid']
    );
  }

  // Include the main module file
  module_load_include('inc', 'addresses');

  // Get other fields from hook_addressesfieldsapi
  $element = array_merge(
    $element,
    module_invoke_all('addressesfieldapi', 'form', $fields, $values)
  );

  return $element;
}

/**
 * Implementation of hook_menu().
 */
function addresses_menu() {
  $items['admin/settings/address'] = array(
    'access arguments'  => array('access administration pages'),
    'description'       => 'Settings for Address module',
    'file'              => 'addresses.settings.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_addresses_settings'),
    'title'             => 'Addresses',
  );
  $items['admin/settings/address/format'] = array(
    'access arguments'  => array('access administration pages'),
    'description'       => 'Format addresses',
    'file'              => 'addresses.settings.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_addresses_settings_format', 4),
    'title'             => 'Addresses Format',
    'type'              => MENU_CALLBACK
  );
  $items['admin/settings/address/autocomplete'] = array(
    'access callback'   => TRUE,
    'file'              => 'addresses.settings.inc',
    'page callback'     => '_addresses_autocomplete',
    'type'              => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function addresses_theme() {
  return array(
    // Shows addresses normally
    'addresses' => array(
      'arguments' => array('address', 'hide'),
      'file'      => 'addresses.inc',
    ),
    // Shows address form elements
    'addresses_elements' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.settings.inc',
    ),
    // Shows address fields
    'addresses_field_city' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_street' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_additional' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_country_name' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_country_code2' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_country_code3' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_postal_code' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_province_name' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_field_province_code' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    // Shows addresses using a single line
    'addresses_address_singleline' => array(
      'arguments' => array('addresses'),
      'file'      => 'addresses.inc',
    ),
    // Choose the addresses fields
    'addresses_settings_fields' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.settings.inc',
    ),
  );
}

/**
 * Implementation of hook_token_list().
 */
function addresses_token_list($type = 'all') {
  if ($type == 'addresses_general') {
    $tokens[t('Addresses: General')]['aname']         = t('Address name.');
    return $tokens;
  }
  elseif ($type == 'addresses_adr') {
    $tokens[t('Addresses: Address')]['street']        = t('Street and number.');
    $tokens[t('Addresses: Address')]['additional']    = t('Street complement, like apartment number.');
    $tokens[t('Addresses: Address')]['province_name'] = t('State/Province full name.');
    $tokens[t('Addresses: Address')]['province_code'] = t('State/Province code.');
    $tokens[t('Addresses: Address')]['country_name']  = t('Country name.');
    $tokens[t('Addresses: Address')]['country_code2'] = t('Country 2-digits code.');
    $tokens[t('Addresses: Address')]['country_code3'] = t('Country 3-digits code.');
    $tokens[t('Addresses: Address')]['postal_code']   = t('Postal code.');
    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 */
function addresses_token_values($type, $object = NULL) {
  if ($type == 'addresses_general') {
    $values['primary']        = empty($object['primary']) ? '' :
      ' ('. t('default') .')';
    $values['aname']          = empty($object['aname']) ? '' :
      '<span class="fn org">'. theme('placeholder', $object['aname']) . $values['primary'] .'</span>';
    return $values;
  }
  elseif ($type == 'addresses_adr') {
    $values['primary']        = empty($object['primary']) ? '' :
      ' ('. t('default') .')';
    $values['aname']          = empty($object['aname']) ? '' :
      '<span class="fn org">'. theme('placeholder', $object['aname']) . $values['primary'] .'</span>';

    $values['street']         = empty($object['street']) ? '' : theme('addresses_field_street', $object);
    $values['additional']     = empty($object['additional']) ? '' : theme('addresses_field_additional', $object);
    $values['city']           = empty($object['city']) ? '' : theme('addresses_field_city', $object);
    $values['postal_code']    = empty($object['postal_code']) ? '' : theme('addresses_field_postal_code', $object);

    $values['province_code']  = (empty($object['province']) and empty($object['country'])) ? '' :
      theme('addresses_field_province_code', $object);
    $values['province_name']  = (empty($object['province']) and empty($object['country'])) ? '' :
      theme('addresses_field_province_name', $object);

    $values['country_code2']  = empty($object['country']) ? '' : theme('addresses_field_country_code2', $object);
    $values['country_code3']  = empty($object['country']) ? '' : theme('addresses_field_country_code3', $object);
    $values['country_name']   = empty($object['country']) ? '' : theme('addresses_field_country_name', $object);

    return $values;
  }
}
