<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file addresses_node.module
 * You can associate a geographic address with content.
 */

define('ADDRESSES_NODE_PATH' , drupal_get_path('module', 'addresses_node'));

/**
 * Implementation of hook_form_alter().
 *
 * It will modify the general behaviour of your node forms.
 */
function addresses_node_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type'])
      and isset($form['#node'])
      and $form['type']['#value'] .'_node_form' == $form_id) {
    include_once ADDRESSES_PATH .'/addresses.inc';

    // Get the address form builder
    _addresses_form($form, 'node', $form['#node']->addresses);
  }
  elseif ($form_id == 'node_type_delete_confirm') {
    $form['#submit'][] = '_addresses_node_node_type_delete';
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function addresses_node_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'delete':
      include_once ADDRESSES_PATH .'/addresses.inc';

      // Delete all addresses linked to this node
      _addresses_address_delete($node->nid, 'node');
      break;
    case 'update':
    case 'insert':
      include_once ADDRESSES_PATH .'/addresses.inc';

      // Save each address
      foreach ($node->addresses as $address) {
        _addresses_address_save($address, $node->nid, 'node');
      }
      break;
    case 'load':
      include_once ADDRESSES_PATH .'/addresses.inc';

      // Load all all addresses linked to this node
      $output['addresses'] = _addresses_address_get($node->nid, 'node');
      return $output;
    case 'view':
      break;
  }
}

/**
 * Delete all traces of this node type
 *
 * @ingroup form
 */
function _addresses_node_node_type_delete($form, &$form_state) {
  variable_del('addresses_node_'. $form_state['values']['type']);
}