<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file addresses.module
 * You can associate a geographic address with content and users.
 */

define('ADDRESSES_PATH' , drupal_get_path('module', 'address'));

/**
 * The address fields can be: displayed, required, hidden or not
 * used at all
 */
define('ADDRESSES_FIELD_NONE',      0);
define('ADDRESSES_FIELD_SHOW',      1);
define('ADDRESSES_FIELD_REQUIRED',  2);
define('ADDRESSES_FIELD_HIDDEN',    3);

/**
 * Implementation of hook_menu().
 */
function addresses_menu() {
  $items['admin/settings/address'] = array(
    'description'     => t('Settings for Address module'),
    'file'            => 'addresses.inc',
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('_addresses_admin'),
    'title'           => t('Addresses'),
  );

  /// @todo use the correct ACCESS PERMISSION
  $items['admin/settings/address/autocomplete'] = array(
    'access'          => TRUE,
    'file'            => 'addresses.inc',
    'page callback'   => '_addresses_autocomplete',
    'type'            => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function addresses_theme() {
  return array(
    'addresses' => array(
      'arguments' => array('address', 'hide'),
      'file'      => 'addresses.inc',
    ),
    'addresses_form' => array(
      'arguments' => array('form'),
      'file'      => 'addresses.inc',
    ),
    'addresses_address_singleline' => array(
      'arguments' => array('addresses'),
      'file'      => 'addresses.inc',
    ),
  );
}
