<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file address_node.module
 * You can associate a geographic address with content.
 */

define('ADDRESS_NODE_PATH' , drupal_get_path('module', 'address_node'));

/**
 * Implementation of hook_address_fields_api().
 */
function address_node_address_fields_api($op) {
  if ($op == 'field') {
  }
  elseif ($op == 'group') {
    return array(
      'user' => array(
        'is_primary'  => ADDRESS_FIELD_SHOW,
        'aname'       => ADDRESS_FIELD_SHOW,
        'street'      => ADDRESS_FIELD_SHOW,
        'city'        => ADDRESS_FIELD_SHOW,
        'province'    => ADDRESS_FIELD_SHOW,
        'postal_code' => ADDRESS_FIELD_SHOW,
        'country'     => ADDRESS_FIELD_SHOW
      )
    );
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * It will modify the general behaviour of your node forms.
 */
function address_node_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type'])
      and isset($form['#node'])
      and $form['type']['#value'] .'_node_form' == $form_id) {
  }
}