<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file addresses_phone.module
 * Use phone and fax fields on .
 */

/**
 * Implementation of hook_addressfieldapi().
 *
 * Its a specific Addresses module hook function, to
 * allow other modules to add more fields to the addresses
 */
function addresses_phone_addressesfieldapi($op, $fields = array(), $values = array()) {
  if ($op == 'form') {
    for ($a = 0; $a < $fields['qty']; $a++) {
      // Telephone number
      if ($fields['phone'] == ADDRESSES_FIELD_HIDDEN) {
        $form[$a]['phone'] = array(
          '#type'           => 'hidden',
          '#value'          => isset($values[$a]['phone']) ? $values[$a]['phone'] : '',
        );
      }
      elseif (!empty($fields['phone'])) {
        $form[$a]['phone'] = array(
          '#type'           => 'textfield',
          '#title'          => t('Phone'),
          '#default_value'  => isset($values[$a]['phone']) ? $values[$a]['phone'] : '',
          '#size'           => 50,
          '#maxlength'      => 75,
          '#attributes'     => NULL,
          '#required'       => ($fields['phone'] == ADDRESSES_FIELD_REQUIRED)
        );
      }

      // Fax number
      if ($fields['fax'] == ADDRESSES_FIELD_HIDDEN) {
        $form[$a]['fax'] = array(
          '#type'           => 'hidden',
          '#value'          => isset($values[$a]['fax']) ? $values[$a]['fax'] : '',
        );
      }
      elseif (!empty($fields['fax'])) {
        $form[$a]['fax'] = array(
          '#type'           => 'textfield',
          '#title'          => t('Fax'),
          '#default_value'  => isset($values[$a]['fax']) ? $values[$a]['fax'] : '',
          '#size'           => 50,
          '#maxlength'      => 75,
          '#attributes'     => NULL,
          '#required'       => ($fields['fax'] == ADDRESSES_FIELD_REQUIRED)
        );
      }
    }

    return $form;
  }
  elseif ($op == 'settings') {
    // This list of options are used many times, so its
    // usefull to create it now an use it later
    $options = array(
      ADDRESSES_FIELD_NONE      => t('None'),
      ADDRESSES_FIELD_SHOW      => t('Normal'),
      ADDRESSES_FIELD_REQUIRED  => t('Required'),
      ADDRESSES_FIELD_HIDDEN    => t('Hidden')
    );

    // List of address fields
    $form['addresses']['phone'] = array(
      '#default_value'  => empty($fields['phone']) ? ADDRESSES_FIELD_NONE : $fields['phone'],
      '#options'        => $options,
      '#title'          => t('Phone'),
      '#type'           => 'radios',
    );
    $form['addresses']['fax'] = array(
      '#default_value'  => empty($fields['fax']) ? ADDRESSES_FIELD_NONE : $fields['fax'],
      '#options'        => $options,
      '#title'          => t('Fax'),
      '#type'           => 'radios',
    );
  }

  return $form;
}
