<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file address_user.module
 * You can associate a geographic address with users.
 */

define('ADDRESS_USER_PATH' , drupal_get_path('module', 'address_user'));

/**
 * Implementation of hook_address_fields_api().
 */
function address_user_address_fields_api($op) {
  if ($op == 'field') {
  }
  elseif ($op == 'group') {
    return array(
      'user' => array(
        'is_primary'  => ADDRESS_FIELD_SHOW,
        'aname'       => ADDRESS_FIELD_SHOW,
        'street'      => ADDRESS_FIELD_SHOW,
        'city'        => ADDRESS_FIELD_SHOW,
        'province'    => ADDRESS_FIELD_SHOW,
        'postal_code' => ADDRESS_FIELD_SHOW,
        'country'     => ADDRESS_FIELD_SHOW
      )
    );
  }
}

/**
 * Implementation of hook_menu().
 */
function address_user_menu() {
  // Add tab for address book.
  $items['user/%user/address'] = array(
    'page callback'   => '_address_user_address',
    'file'            => 'address_user.inc',
    'title'           => t('Address Book'),
    'type'            => MENU_LOCAL_TASK,
    'weight'          => 1,
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function address_user_theme() {
  return array(
    'address_user_overview' => array(
      'arguments' => array('uid', 'addresses'),
      'file'      => 'address.inc',
    ),
  );
}

/**
 * Implementation of hook_user().
 */
function address_user_user($op, &$edit, &$user) {
  if ($op == 'delete') {
    include_once ADDRESS_PATH .'/address.inc';
    _address_address_delete($user->uid, 'user');
  }
}
