<?php
// $Id$
/**
 * @author Bruno Massa
 * @file addresses_user.module
 * You can associate a geographic address with users.
 */

/**
 * Check if user is allowed to have a address book.
 *
 * @param $account
 *   Object. The current user account
 * @return
 *   Boolean. If the user can or canont access the page
 */
function _addresses_user_access($account) {
  global $user;
  if ($account->uid == $user->uid
      and variable_get('addresses_user_book', FALSE)
      and user_access('create addess book', $account)) {
    return TRUE;
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Let admin select what addresses fields are relevant.
 */
function addresses_user_form__addresses_settings_alter(&$form, &$form_state) {
  module_load_include('settings.inc', 'addresses');
  $form += _addresses_settings_fields(variable_get('addresses_user', array()));

  // Set the 'addresses' as a fieldset
  $form['addresses_user'] = array(
    '#description'  => t('Choose what fields user addresses might have'),
    '#title'        => t('User addresses fields'),
    '#tree'         => TRUE,
    '#type'         => 'fieldset',
  ) + $form['addresses'];

  unset($form['addresses']);

  // Other options
  $form['addresses_user_book'] = array(
    '#default_value'  => variable_get('addresses_user_book', FALSE),
    '#description'    => t('Users might have several addresses, like a address book.'),
    '#title'          => t('Address book'),
    '#type'           => 'checkbox',
  );
  $form['addresses_user_register'] = array(
    '#default_value'  => variable_get('addresses_user_register', FALSE),
    '#title'          => t('Address form on registration'),
    '#tree'           => FALSE,
    '#type'           => 'checkbox',
  );
}

/**
 * Implementation of hook_form_alter().
 *
 * Put the address form into the registration form.
 */
function addresses_user_form_user_register_alter(&$form, &$form_state) {
  if (variable_get('addresses_user_register', FALSE)) {
    addresses_user_form_user_profile_form_alter($form, $form_state, TRUE);
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Put the address form into the user form.
 */
function addresses_user_form_user_profile_form_alter(&$form, &$form_state, $register = FALSE) {
  if (!variable_get('addresses_user_book', FALSE)) {
    if (empty($register)) {
      global $user;
      module_load_include('inc', 'addresses_user');
      $addresses = _addresses_user_address_get($user->uid, 'user');
      $address = $addresses[0];
    }

    // Get the fields used on this address
    $fields = variable_get('addresses_user', array());

    // If its the very first time its loaded, use all fields
    if (empty($fields)) {
      $ftypes = module_invoke_all('addressesfieldapi', 'fields');
      foreach ($ftypes as $ftype => $field) {
        // List of address fields
        $fields[$index] = empty($field_values[$ftype]) ? $field['display'] : $field_values[$ftype];
      }
    }

    // Get the address form builder
    $form['addresses'] = array(
      '#default_value'  => empty($address) ? array() : $address,
      '#fields'         => $fields,
      '#required'       => TRUE,
      '#type'           => 'addresses_elements',
      '#tree'           => TRUE
    );

    $form['#submit'][] = '_addresses_user_form_submit';
  }
}

/**
 * Implementation of hook_menu().
 */
function addresses_user_menu() {
  // Add tab for address book.
  $items['user/%user/address'] = array(
    'access callback'   => '_addresses_user_access',
    'access arguments'  => array(1),
    'page callback'     => '_addresses_user_address',
    'file'              => 'addresses_user.inc',
    'title'             => t('Address Book'),
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 1,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function addresses_user_perm() {
  return array('create addess book');
}

/**
 * Implementation of hook_theme().
 */
function addresses_user_theme() {
  return array(
    'addresses_user_overview' => array(
      'arguments' => array('uid', 'addresses'),
      'file'      => 'addresses_user.inc',
    ),
  );
}

/**
 * Implementation of hook_token_list().
 *
 * It basicly list all token values that are allowed to
 * be used. A brief description is also possible.
 */
function addresses_user_token_list($type = 'all') {
  if ($type == 'node' or $type == 'all') {
    $tokens['addresses']['address-name']         = t('Address name');
    $tokens['addresses']['address-street']       = t('Street');
    $tokens['addresses']['address-additional']   = t('Additional');
    $tokens['addresses']['address-city']         = t('City');
    $tokens['addresses']['address-province']     = t('State/Province code');
    $tokens['addresses']['address-provincename'] = t('State/Province name');
    $tokens['addresses']['address-country']      = t('Country code');
    $tokens['addresses']['address-countryname']  = t('Country name');
    $tokens['addresses']['address-postal_code']  = t('Postal code');

    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 *
 * It converts all token string into the real values.
 */
function addresses_user_token_values($type, $object = NULL) {
  if ($type == 'user') {
    global $user;

    module_load_include('inc', 'addresses_user');

    if ($address = _addresses_user_address_get($user->uid, 'user') and !empty($address[0])) {
      // Include the propper .inc file
      module_load_include('inc', 'addresses');

      // Get a list of countries
      $countries = _addresses_country_get(variable_get('addresses_country_list', array()));

      // Get a list of provinces of the given country
      $provincenames = _addresses_province_get(strtolower($address[0]['country']));

      // Set a list of Token values
      $values['address-name']         = check_plain($address[0]['name']);
      $values['address-street']       = check_plain($address[0]['street']);
      $values['address-additional']   = check_plain($address[0]['additional']);
      $values['address-city']         = check_plain($address[0]['city']);
      $values['address-province']     = check_plain($address[0]['province']);
      $values['address-provincename'] = check_plain($provincenames[$address[0]['province']]);
      $values['address-postal_code']  = check_plain($address[0]['postal_code']);
      $values['address-country']      = check_plain($address[0]['country']);
      $values['address-countryname']  = check_plain($countries[$address[0]['country']]);
    }

    return $values;
  }
}

/**
 * Implementation of hook_user().
 */
function addresses_user_user($op, &$edit, &$user) {
  if ($op == 'delete') {
    module_load_include('inc', 'addresses_user');
    _addresses_user_address_delete($user->uid, 'user');
  }
  elseif ($op == 'view' and !variable_get('addresses_user_book', FALSE)) {
    module_load_include('inc', 'addresses_user');
    $addresses = _addresses_user_address_get($user->uid, 'user');
    $address = $addresses[0];
    $user->content['addresses'][] =  array(
      '#type' => 'user_profile_item',
      '#title' => t('Address'),
      '#value' => theme('addresses', $address),
    );
  }
}
