<?php
// $Id$
/**
 * @author Bruno Massa
 * @file
 * Use phone and fax fields on .
 */

/**
 * Implementation of hook_addressfieldapi().
 *
 * Its a specific Addresses module hook function, to
 * allow other modules to add more fields to the addresses
 */
function addresses_phone_addressesfieldapi($op, $fields = array(), $values = array()) {
  if ($op == 'fields') {
    return array(
      'phone' => array(
        'type'        => 'varchar',
        'length'      => 16,
        'description' => t('Phone numbers, like cellphone, home, office'),
        'display'     => ADDRESSES_FIELD_NONE,
        'title'       => t('Phone'),
        'theme'       => array(
          'phone'         => t('Phone number.'),
        ),
        'token'       => 'addresses_general',
      ),
      'fax' => array(
        'type'        => 'varchar',
        'length'      => 16,
        'description' => t('Fax number'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Fax'),
        'theme'       => array(
          'fax'           => t('Fax.'),
        ),
        'token'       => 'addresses_general',
      ),
    );
  }
  elseif ($op == 'form') {
    // Telephone number
    if ($fields['phone'] == ADDRESSES_FIELD_HIDDEN) {
      $form['phone'] = array(
        '#type'           => 'hidden',
        '#value'          => isset($values['phone']) ? $values['phone'] : '',
      );
    }
    elseif (!empty($fields['phone'])) {
      $form['phone'] = array(
        '#type'           => 'textfield',
        '#title'          => t('Phone'),
        '#default_value'  => isset($values['phone']) ? $values['phone'] : '',
        '#size'           => 50,
        '#maxlength'      => 75,
        '#attributes'     => NULL,
        '#required'       => ($fields['phone'] == ADDRESSES_FIELD_REQUIRED)
      );
    }

    // Fax number
    if ($fields['fax'] == ADDRESSES_FIELD_HIDDEN) {
      $form['fax'] = array(
        '#type'           => 'hidden',
        '#value'          => isset($values['fax']) ? $values['fax'] : '',
      );
    }
    elseif (!empty($fields['fax'])) {
      $form['fax'] = array(
        '#type'           => 'textfield',
        '#title'          => t('Fax'),
        '#default_value'  => isset($values['fax']) ? $values['fax'] : '',
        '#size'           => 50,
        '#maxlength'      => 75,
        '#attributes'     => NULL,
        '#required'       => ($fields['fax'] == ADDRESSES_FIELD_REQUIRED)
      );
    }

    return $form;
  }
}

/**
 * Implementation of hook_theme().
 */
function addresses_phone_theme() {
  return array(
    // Shows address fields
    'addresses_field_phone' => array(
      'arguments' => array('form'),
//       'file'      => 'addresses_phone.theme.inc',
    ),
    'addresses_field_fax' => array(
      'arguments' => array('form'),
//       'file'      => 'addresses_phone.theme.inc',
    ),
  );
}

/**
 * Print the field Phone.
 *
 * @param $afields
 *   Array. All field values
 * @ingroup themeable
 */
function theme_addresses_field_phone($afields) {
  return '<dt>'. t('Phone') .': </dt><dd class="phone">'. $afields['phone'] .'</dd>';
}

/**
 * Print the field Fax.
 *
 * @param $afields
 *   Array. All field values
 * @ingroup themeable
 */
function theme_addresses_field_fax($afields) {
  return '<dt>'. t('Fax') .': </dt><dd class="fax">'. $afields['phone'] .'</dd>';
}
