<?php
/**
 * $Id$
 * @author Bruno Massa
 * @file addresses_phone.module
 * Use phone and fax fields on .
 */

/**
 * Implementation of hook_addressfieldapi().
 *
 * Its a specific Addresses module hook function, to
 * allow other modules to add more fields to the addresses
 */
function addresses_phone_addressesfieldapi($op, $fields = array(), $values = array()) {
  if ($op == 'fields') {
    return array(
      'phone' => array(
        'type'        => 'int',
        'description' => t('Phone numbers, like cellphone, home, office'),
        'display'     => ADDRESSES_FIELD_NONE,
        'title'       => t('Phone'),
      ),
      'fax' => array(
        'type'        => 'int',
        'description' => t('Fax number'),
        'display'     => ADDRESSES_FIELD_SHOW,
        'title'       => t('Fax'),
      ),
    );
  }
  elseif ($op == 'form') {
    // Telephone number
    if ($fields['phone'] == ADDRESSES_FIELD_HIDDEN) {
      $form['phone'] = array(
        '#type'           => 'hidden',
        '#value'          => isset($values['phone']) ? $values['phone'] : '',
      );
    }
    elseif (!empty($fields['phone'])) {
      $form['phone'] = array(
        '#type'           => 'textfield',
        '#title'          => t('Phone'),
        '#default_value'  => isset($values['phone']) ? $values['phone'] : '',
        '#size'           => 50,
        '#maxlength'      => 75,
        '#attributes'     => NULL,
        '#required'       => ($fields['phone'] == ADDRESSES_FIELD_REQUIRED)
      );
    }

    // Fax number
    if ($fields['fax'] == ADDRESSES_FIELD_HIDDEN) {
      $form['fax'] = array(
        '#type'           => 'hidden',
        '#value'          => isset($values['fax']) ? $values['fax'] : '',
      );
    }
    elseif (!empty($fields['fax'])) {
      $form['fax'] = array(
        '#type'           => 'textfield',
        '#title'          => t('Fax'),
        '#default_value'  => isset($values['fax']) ? $values['fax'] : '',
        '#size'           => 50,
        '#maxlength'      => 75,
        '#attributes'     => NULL,
        '#required'       => ($fields['fax'] == ADDRESSES_FIELD_REQUIRED)
      );
    }

    return $form;
  }
}
