<?php
// $Id$

// Barbados

function addresses_province_list_bb() {
  return array(
    'CC' => t('Christ Church'),
    'AND' => t('Saint Andrew'),
    'GEO' => t('Saint George'),
    'JAM' => t('Saint James'),
    'JOH' => t('Saint John'),
    'JOS' => t('Saint Joseph'),
    'LUC' => t('Saint Lucy'),
    'MIC' => t('Saint Michael'),
    'PET' => t('Saint Peter'),
    'PHI' => t('Saint Philip'),
    'THO' => t('Saint Thomas')
  );
}
