<?php
// $Id$

// Burundi

function addresses_province_list_bi() {
  return array(
    'BB' => t('Bubanza'),
    'BJ' => t('Bujumbura'),
    'BR' => t('Bururi'),
    'CA' => t('Cankuzo'),
    'CI' => t('Cibitoke'),
    'GI' => t('Gitega'),
    'KR' => t('Karuzi'),
    'KY' => t('Kayanza'),
    'KI' => t('Kirundo'),
    'MA' => t('Makamba'),
    'MU' => t('Muramvya'),
    'MY' => t('Muyinga'),
    'MW' => t('Mwaro'),
    'NG' => t('Ngozi'),
    'RT' => t('Rutana'),
    'RY' => t('Ruyigi')
  );
}
