<?php
// $Id$

// Bermuda

function addresses_province_list_bm() {
  return array(
    'DS' => t('Devonshire'),
    'HC' => t('Hamilton City'),
    'HA' => t('Hamilton'),
    'PG' => t('Paget'),
    'PB' => t('Pembroke'),
    'GC' => t('Saint George City'),
    'SG' => t("Saint George's"),
    'SA' => t('Sandys'),
    'SM' => t("Smith's"),
    'SH' => t('Southampton'),
    'WA' => t('Warwick')
  );
}
