<?php
// $Id$

// Bolivia

function addresses_province_list_bo() {
  return array(
    'BEN' => t('Departmento Beni'),
    'CHU' => t('Departmento Chuquisaca'),
    'COC' => t('Departmento Cochabamba'),
    'LPZ' => t('Departmento La Paz'),
    'ORU' => t('Departmento Oruro'),
    'PAN' => t('Departmento Pando'),
    'POT' => t('Departmento Potosi'),
    'SCZ' => t('Departmento Santa Cruz'),
    'TAR' => t('Departmento Tarija')
  );
}
