<?php
// $Id$

// Congo, The Democratic Republic of the

function addresses_province_list_cd() {
  return array(
    'BC' => t('Bas-Congo'),
    'BN' => t('Bandundu'),
    'EQ' => t('Equateur'),
    'KA' => t('Katanga'),
    'KE' => t('Kasai-Oriental'),
    'KN' => t('Kinshasa'),
    'KW' => t('Kasai-Occidental'),
    'MA' => t('Maniema'),
    'NK' => t('Nord-Kivu'),
    'OR' => t('Orientale'),
    'SK' => t('Sud-Kivu')
  );
}
