<?php
// $Id$

// Chile

function addresses_province_list_cl() {
  return array(
    'AI' => t('Aisen del General Carlos Ibanez del Campo (XI)'),
    'AN' => t('Antofagasta (II)'),
    'AR' => t('Araucania (IX)'),
    'AT' => t('Atacama (III)'),
    'BI' => t('Bio-Bio (VIII)'),
    'CO' => t('Coquimbo (IV)'),
    'LI' => t("Libertador General Bernardo O'Higgins (VI)"),
    'LL' => t('Los Lagos (X)'),
    'MA' => t('Magallanes (XII)'),
    'ML' => t('Maule (VII)'),
    'RM' => t('Region Metropolitana (RM)'),
    'TA' => t('Tarapaca (I)'),
    'VS' => t('Valparaiso (V)')
  );
}
