<?php
// $Id$

// Denmark

function addresses_province_list_dk() {
  return array(
    'CC' => t('Copenhagen (municipality)'),
    'FC' => t('Frederiksberg (municipality)'),
    'CO' => t('Copenhagen'),
    'FR' => t('Frederiksborg'),
    'RO' => t('Roskilde'),
    'WZ' => t('West Zealand'),
    'ST' => t('Storstrom'),
    'FU' => t('Funen'),
    'SJ' => t('South Jutland'),
    'RB' => t('Ribe'),
    'VK' => t('Vejle'),
    'RK' => t('Ringkjobing'),
    'VB' => t('Viborg'),
    'NJ' => t('North Jutland'),
    'AR' => t('Arhus'),
    'BH' => t('Bornholm'),
    'GL' => t('Greenland'),
    'FO' => t('Faroe Islands')
  );
}
