<?php
// $Id$

// Dominica

function addresses_province_list_dm() {
  return array(
    'AND' => t('Saint Andrew Parish'),
    'DAV' => t('Saint David Parish'),
    'GEO' => t('Saint George Parish'),
    'JOH' => t('Saint John Parish'),
    'JOS' => t('Saint Joseph Parish'),
    'LUK' => t('Saint Luke Parish'),
    'MAR' => t('Saint Mark Parish'),
    'PAT' => t('Saint Patrick Parish'),
    'PAU' => t('Saint Paul Parish'),
    'PET' => t('Saint Peter Parish')
  );
}
