<?php
// $Id$

// Ethiopia

function addresses_province_list_et() {
  return array(
    'AF' => t('Afar'),
    'AH' => t('Amhara'),
    'BG' => t('Benishangul-Gumaz'),
    'GB' => t('Gambela'),
    'HR' => t('Hariai'),
    'OR' => t('Oromia'),
    'SM' => t('Somali'),
    'SN' => t('Southern Nations - Nationalities and Peoples Region'),
    'TG' => t('Tigray'),
    'AA' => t('Addis Ababa'),
    'DD' => t('Dire Dawa')
  );
}
