<?php
// $Id$

// Georgia

function addresses_province_list_ge() {
  return array(
    'AB' => t('Abkhazia'),
    'AJ' => t('Ajaria'),
    'TB' => t('Tbilisi'),
    'GU' => t('Guria'),
    'IM' => t('Imereti'),
    'KA' => t('Kakheti'),
    'KK' => t('Kvemo Kartli'),
    'MM' => t('Mtskheta-Mtianeti'),
    'RL' => t('Racha Lechkhumi and Kvemo Svaneti'),
    'SZ' => t('Samegrelo-Zemo Svaneti'),
    'SJ' => t('Samtskhe-Javakheti'),
    'SK' => t('Shida Kartli')
  );
}
