<?php
// $Id$

// Gambia

function addresses_province_list_gm() {
  return array(
    'BJ' => t('Banjul'),
    'BS' => t('Basse'),
    'BR' => t('Brikama'),
    'JA' => t('Janjangbure'),
    'KA' => t('Kanifeng'),
    'KE' => t('Kerewan'),
    'KU' => t('Kuntaur'),
    'MA' => t('Mansakonko'),
    'LR' => t('Lower River'),
    'CR' => t('Central River'),
    'NB' => t('North Bank'),
    'UR' => t('Upper River'),
    'WE' => t('Western')
  );
}
