<?php
// $Id$

// Honduras

function addresses_province_list_hn() {
  return array(
    'AT' => t('Atlantida'),
    'CH' => t('Choluteca'),
    'CL' => t('Colon'),
    'CM' => t('Comayagua'),
    'CP' => t('Copan'),
    'CR' => t('Cortes'),
    'PA' => t('El Paraiso'),
    'FM' => t('Francisco Morazan'),
    'GD' => t('Gracias a Dios'),
    'IN' => t('Intibuca'),
    'IB' => t('Islas de la Bahia (Bay Islands)'),
    'PZ' => t('La Paz'),
    'LE' => t('Lempira'),
    'OC' => t('Ocotepeque'),
    'OL' => t('Olancho'),
    'SB' => t('Santa Barbara'),
    'VA' => t('Valle'),
    'YO' => t('Yoro')
  );
}
