<?php
// $Id$

// Iraq

function addresses_province_list_iq() {
  return array(
    'BD' => t('Baghdad'),
    'SD' => t('Salah ad Din'),
    'DY' => t('Diyala'),
    'WS' => t('Wasit'),
    'MY' => t('Maysan'),
    'BA' => t('Al Basrah'),
    'DQ' => t('Dhi Qar'),
    'MU' => t('Al Muthanna'),
    'QA' => t('Al Qadisyah'),
    'BB' => t('Babil'),
    'KB' => t('Al Karbala'),
    'NJ' => t('An Najaf'),
    'AB' => t('Al Anbar'),
    'NN' => t('Ninawa'),
    'DH' => t('Dahuk'),
    'AL' => t('Arbil'),
    'TM' => t("At Ta'mim"),
    'SL' => t('As Sulaymaniyah')
  );
}
