<?php
// $Id$

// Jamaica

function addresses_province_list_jm() {
  return array(
    'CLA' => t('Clarendon Parish'),
    'HAN' => t('Hanover Parish'),
    'KIN' => t('Kingston Parish'),
    'MAN' => t('Manchester Parish'),
    'POR' => t('Portland Parish'),
    'AND' => t('Saint Andrew Parish'),
    'ANN' => t('Saint Ann Parish'),
    'CAT' => t('Saint Catherine Parish'),
    'ELI' => t('Saint Elizabeth Parish'),
    'JAM' => t('Saint James Parish'),
    'MAR' => t('Saint Mary Parish'),
    'THO' => t('Saint Thomas Parish'),
    'TRL' => t('Trelawny Parish'),
    'WML' => t('Westmoreland Parish')
  );
}
