<?php
// $Id$

// Jordan

function addresses_province_list_jo() {
  return array(
    'AJ' => t('Ajlun'),
    'AQ' => t("Al 'Aqabah"),
    'BA' => t("Al Balqa'"),
    'KA' => t('Al Karak'),
    'MF' => t('Al Mafraq'),
    'AM' => t("'Amman"),
    'TA' => t('At Tafilah'),
    'ZA' => t("Az Zarqa'"),
    'IR' => t('Irbid'),
    'JA' => t('Jarash'),
    'MN' => t("Ma'an"),
    'MD' => t('Madaba')
  );
}
