<?php
// $Id$

// Kazakhstan

function addresses_province_list_kz() {
  return array(
    'ALA' => t('Almaty'),
    'AST' => t('Astana'),
    'ALM' => t('Almaty'),
    'AKM' => t('Aqmola'),
    'AKT' => t('Aqtobe'),
    'ATY' => t('Atyrau'),
    'ZAP' => t('Baty Qazaqstan'),
    'MAN' => t('Mangghystau'),
    'YUZ' => t('Ongtustik Qazaqstan'),
    'PAV' => t('Paylodar'),
    'KAR' => t('Qaraghandy'),
    'KUS' => t('Qustanay'),
    'KZY' => t('Qyzylorda'),
    'VOS' => t('Shyghys Qazaqstan'),
    'SEV' => t('Soltustik Qazaqstan'),
    'ZHA' => t('Zhambyl')
  );
}
