<?php
// $Id$

// Lao People's Democratic Republic

function addresses_province_list_la() {
  return array(
    'VT' => t('Vientiane'),
    'AT' => t('Attapu'),
    'BK' => t('Bokeo'),
    'BL' => t('Bolikhamxai'),
    'CH' => t('Champasak'),
    'HO' => t('Houaphan'),
    'KH' => t('Khammouan'),
    'LM' => t('Louang Namtha'),
    'LP' => t('Louangphabang'),
    'OU' => t('Oudomxai'),
    'PH' => t('Phongsali'),
    'SL' => t('Salavan'),
    'SV' => t('Savannakhet'),
    'VI' => t('Vientiane'),
    'XA' => t('Xaignabouli'),
    'XE' => t('Xekong'),
    'XI' => t('Xiangkhoang'),
    'XN' => t('Xaisomboun')
  );
}
