<?php
// $Id$

// Liberia

function addresses_province_list_lr() {
  return array(
    'BI' => t('Bomi'),
    'BG' => t('Bong'),
    'GB' => t('Grand Bassa'),
    'CM' => t('Grand Cape Mount'),
    'GG' => t('Grand Gedeh'),
    'GK' => t('Grand Kru'),
    'LO' => t('Lofa'),
    'MG' => t('Margibi'),
    'ML' => t('Maryland'),
    'MS' => t('Montserrado'),
    'NB' => t('Nimba'),
    'RC' => t('River Cess'),
    'SN' => t('Sinoe')
  );
}
