<?php
// $Id$

// Luxembourg

function addresses_province_list_lu() {
  return array(
    'DD' => t('Diekirch'),
    'DC' => t('Clervaux'),
    'DR' => t('Redange'),
    'DV' => t('Vianden'),
    'DW' => t('Wiltz'),
    'GG' => t('Grevenmacher'),
    'GE' => t('Echternach'),
    'GR' => t('Remich'),
    'LL' => t('Luxembourg'),
    'LC' => t('Capellen'),
    'LE' => t('Esch-sur-Alzette'),
    'LM' => t('Mersch')
  );
}
