<?php
// $Id$

// Myanmar

function addresses_province_list_mm() {
  return array(
    'AY' => t('Ayeyarwady'),
    'BG' => t('Bago'),
    'MG' => t('Magway'),
    'MD' => t('Mandalay'),
    'SG' => t('Sagaing'),
    'TN' => t('Tanintharyi'),
    'YG' => t('Yangon'),
    'CH' => t('Chin State'),
    'KC' => t('Kachin State'),
    'KH' => t('Kayah State'),
    'KN' => t('Kayin State'),
    'MN' => t('Mon State'),
    'RK' => t('Rakhine State'),
    'SH' => t('Shan State')
  );
}
