<?php
// $Id$

// Mauritania

function addresses_province_list_mr() {
  return array(
    'AD' => t('Adrar'),
    'AS' => t('Assaba'),
    'BR' => t('Brakna'),
    'DN' => t('Dakhlet Nouadhibou'),
    'GO' => t('Gorgol'),
    'GM' => t('Guidimaka'),
    'HC' => t('Hodh Ech Chargui'),
    'HG' => t('Hodh El Gharbi'),
    'IN' => t('Inchiri'),
    'TA' => t('Tagant'),
    'TZ' => t('Tiris Zemmour'),
    'TR' => t('Trarza'),
    'NO' => t('Nouakchott')
  );
}
