<?php
// $Id$

// Netherlands

function addresses_province_list_nl() {
  return array(
    'DR' => t('Drenthe'),
    'FL' => t('Flevoland'),
    'FR' => t('Friesland'),
    'GE' => t('Gelderland'),
    'GR' => t('Groningen'),
    'LI' => t('Limburg'),
    'NB' => t('Noord Brabant'),
    'NH' => t('Noord Holland'),
    'OV' => t('Overijssel'),
    'UT' => t('Utrecht'),
    'ZE' => t('Zeeland'),
    'ZH' => t('Zuid Holland')
  );
}
