<?php
// $Id$

// Nepal

function addresses_province_list_np() {
  return array(
    'BA' => t('Bagmati'),
    'BH' => t('Bheri'),
    'DH' => t('Dhawalagiri'),
    'GA' => t('Gandaki'),
    'JA' => t('Janakpur'),
    'KA' => t('Karnali'),
    'KO' => t('Kosi'),
    'LU' => t('Lumbini'),
    'MA' => t('Mahakali'),
    'ME' => t('Mechi'),
    'NA' => t('Narayani'),
    'RA' => t('Rapti'),
    'SA' => t('Sagarmatha'),
    'SE' => t('Seti')
  );
}
