<?php
// $Id$

// Nauru

function addresses_province_list_nr() {
  return array(
    'AO' => t('Aiwo'),
    'AA' => t('Anabar'),
    'AT' => t('Anetan'),
    'AI' => t('Anibare'),
    'BA' => t('Baiti'),
    'BO' => t('Boe'),
    'BU' => t('Buada'),
    'DE' => t('Denigomodu'),
    'EW' => t('Ewa'),
    'IJ' => t('Ijuw'),
    'ME' => t('Meneng'),
    'NI' => t('Nibok'),
    'UA' => t('Uaboe'),
    'YA' => t('Yaren')
  );
}
