<?php
// $Id$

// New Zealand

function addresses_province_list_nz() {
  return array(
    'AUK' => t('Auckland'),
    'BOP' => t('Bay of Plenty'),
    'CAN' => t('Canterbury'),
    'GIS' => t('Gisborne'),
    'HKB' => t("Hawke's Bay"),
    'MBH' => t('Marlborough'),
    'MWT' => t('Manawatu-Wanganui'),
    'NSN' => t('Nelson'),
    'NTL' => t('Northland'),
    'OTA' => t('Otago'),
    'STL' => t('Southland'),
    'TAS' => t('Tasman'),
    'TKI' => t('Taranaki'),
    'WGN' => t('Wellington'),
    'WKO' => t('Waikato'),
    'WTC' => t('West Coast')
  );
}
