<?php
// $Id$

// Palau

function addresses_province_list_pw() {
  return array(
    'AM' => t('Aimeliik'),
    'AR' => t('Airai'),
    'AN' => t('Angaur'),
    'HA' => t('Hatohobei'),
    'KA' => t('Kayangel'),
    'KO' => t('Koror'),
    'ME' => t('Melekeok'),
    'NA' => t('Ngaraard'),
    'NG' => t('Ngarchelong'),
    'ND' => t('Ngardmau'),
    'NT' => t('Ngatpang'),
    'NC' => t('Ngchesar'),
    'NR' => t('Ngeremlengui'),
    'NW' => t('Ngiwal'),
    'PE' => t('Peleliu'),
    'SO' => t('Sonsorol')
  );
}
