<?php
// $Id$

// Paraguay

function addresses_province_list_py() {
  return array(
    'AG' => t('Alto Paraguay'),
    'AN' => t('Alto Parana'),
    'AM' => t('Amambay'),
    'AS' => t('Asuncion'),
    'BO' => t('Boqueron'),
    'CG' => t('Caaguazu'),
    'CZ' => t('Caazapa'),
    'CN' => t('Canindeyu'),
    'CE' => t('Central'),
    'CC' => t('Concepcion'),
    'CD' => t('Cordillera'),
    'GU' => t('Guaira'),
    'IT' => t('Itapua'),
    'MI' => t('Misiones'),
    'NE' => t('Neembucu'),
    'PA' => t('Paraguari'),
    'PH' => t('Presidente Hayes'),
    'SP' => t('San Pedro')
  );
}
