<?php
// $Id$

// Rwanda

function addresses_province_list_rw() {
  return array(
    'BU' => t('Butare'),
    'BY' => t('Byumba'),
    'CY' => t('Cyangugu'),
    'GK' => t('Gikongoro'),
    'GS' => t('Gisenyi'),
    'GT' => t('Gitarama'),
    'KG' => t('Kibungo'),
    'KY' => t('Kibuye'),
    'KR' => t('Kigali Rurale'),
    'KV' => t('Kigali-ville'),
    'RU' => t('Ruhengeri'),
    'UM' => t('Umutara')
  );
}
