<?php
// $Id$

// Chad

function addresses_province_list_td() {
  return array(
    'BA' => t('Batha'),
    'BI' => t('Biltine'),
    'BE' => t('Borkou-Ennedi-Tibesti'),
    'CB' => t('Chari-Baguirmi'),
    'GU' => t('Guera'),
    'KA' => t('Kanem'),
    'LA' => t('Lac'),
    'LC' => t('Logone Occidental'),
    'LR' => t('Logone Oriental'),
    'MK' => t('Mayo-Kebbi'),
    'MC' => t('Moyen-Chari'),
    'OU' => t('Ouaddai'),
    'SA' => t('Salamat'),
    'TA' => t('Tandjile')
  );
}
