<?php
// $Id$

// Timor Leste

function addresses_province_list_tl() {
  return array(
    'AL' => t('Aileu'),
    'AN' => t('Ainaro'),
    'BA' => t('Baucau'),
    'BO' => t('Bobonaro'),
    'CO' => t('Cova Lima'),
    'DI' => t('Dili'),
    'ER' => t('Ermera'),
    'LA' => t('Lautem'),
    'LI' => t('Liquica'),
    'MT' => t('Manatuto'),
    'MF' => t('Manufahi'),
    'OE' => t('Oecussi'),
    'VI' => t('Viqueque')
  );
}
