<?php
// $Id$

// United States Minor Outlying Islands

function addresses_province_list_um() {
  return array(
    'BI' => t('Baker Island'),
    'HI' => t('Howland Island'),
    'JI' => t('Jarvis Island'),
    'JA' => t('Johnston Atoll'),
    'KR' => t('Kingman Reef'),
    'MA' => t('Midway Atoll'),
    'NI' => t('Navassa Island'),
    'PA' => t('Palmyra Atoll'),
    'WI' => t('Wake Island')
  );
}
