<?php
// $Id$

// Uzbekistan

function addresses_province_list_uz() {
  return array(
    'AN' => t('Andijon'),
    'BU' => t('Buxoro'),
    'FA' => t("Farg'ona"),
    'JI' => t('Jizzax'),
    'NG' => t('Namangan'),
    'NW' => t('Navoiy'),
    'QA' => t('Qashqadaryo'),
    'QR' => t("Qoraqalpog'iston Republikasi"),
    'SA' => t('Samarqand'),
    'SI' => t('Sirdaryo'),
    'SU' => t('Surxondaryo'),
    'TK' => t('Toshkent city'),
    'TO' => t('Toshkent region'),
    'XO' => t('Xorazm')
  );
}
