<?php
// $Id$

// Zambia

function addresses_province_list_zm() {
  return array(
    'CE' => t('Central Province'),
    'CB' => t('Copperbelt Province'),
    'EA' => t('Eastern Province'),
    'LP' => t('Luapula Province'),
    'LK' => t('Lusaka Province'),
    'NO' => t('Northern Province'),
    'NW' => t('North-Western Province'),
    'SO' => t('Southern Province'),
    'WE' => t('Western Province')
  );
}
