<?php
// $Id$

// Zimbabwe

function addresses_province_list_zw() {
  return array(
    'BU' => t('Bulawayo (city)'),
    'HA' => t('Harare (city)'),
    'ML' => t('Manicaland'),
    'MC' => t('Mashonaland Central'),
    'ME' => t('Mashonaland East'),
    'MW' => t('Mashonaland West'),
    'MV' => t('Masvingo'),
    'MN' => t('Matabeleland North'),
    'MS' => t('Matabeleland South'),
    'MD' => t('Midlands')
  );
}
